# Generated by Django 6.0.5 on 2026-08-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_attributes_alter_product_featured_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductAttribute",
        ),
    ]
