# Generated by Django 6.0.5 on 2026-06-20 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="views",
            field=models.ManyToManyField(
                related_name="views", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="condition",
            field=models.CharField(
                choices=[("New", "New"), ("Used", "Used"), ("Like New", "Like New")],
                max_length=50,
            ),
        ),
    ]
