# Generated by Django 6.0.5 on 2026-07-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(default="📦", max_length=1),
        ),
    ]
