# Generated by Django 6.0.5 on 2026-07-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_category_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="condition",
            field=models.CharField(default="New", max_length=50),
        ),
    ]
