# Generated by Django 6.0.5 on 2026-07-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_product_is_featured_alter_product_condition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_featured",
        ),
        migrations.AddField(
            model_name="product",
            name="featured",
            field=models.CharField(default="NR", max_length=100),
        ),
    ]
