# Generated by Django 6.0.5 on 2026-08-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpverification",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="otpverification",
            name="attempt",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="otpverification",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="otpverification",
            name="otp",
            field=models.CharField(max_length=255),
        ),
    ]
