# Generated by Django 6.0.5 on 2026-08-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_otpverification_active_otpverification_attempt_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="otpverification",
            old_name="active",
            new_name="is_active",
        ),
        migrations.AddField(
            model_name="otpverification",
            name="blocked_until",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
