# Generated by Django 6.0.5 on 2026-06-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_otpverification_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpverification",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
