# Generated by Django 6.0.5 on 2026-07-01 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Report",
        ),
    ]
