# Generated by Django 6.0.5 on 2026-07-09 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_category_icon"),
        ("reports", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="products.product"
            ),
        ),
    ]
